### ISSUE TITLE
Rename package to avoid user confusion

### ISSUE THREAD

**Issue by jennybc** [tidylab/usethis2#19]
Hi, I just returned from a week away, hence the delay. I'm the maintainer of the usethis package.

While I appreciate the homage to usethis, I'm writing to request that you rename the usethis2 package to something less easily confused with usethis.

In the R community, I think it's assumed that a foo2 package is a reboot of or a successor to the foo package (à la ggplot2) and, when it happens, it's also generally a product of the foo authors. Ownership by the tidylab organization could easily reinforce such confusion, in this case.

I think [this twitter thread](https://twitter.com/mdsumner/status/1425065585382019072) captures the prevailing perception of what a "2" package signifies.

I'm actually a bit surprised that CRAN accepted it. I believe this phenomenon may be disallowed in some other language's repositories, since it's moving towards a gray area with typo squatting, in terms of people installing one thing, assuming they're getting another.

Would you be willing to re-release this package under a different name?

**Comment by harell** [comment]
I renamed `usethis2` to `usethat` and asked CRAN to archive `usethis2`.

Cheers

**Comment by hadley** [comment]
This still seems like a rather confusing name to me, but it's at least better than before.

**Comment by jennybc** [comment]
Thanks @harell, I think usethat is less confusing than usethis2.
